server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auditdb
    username: postgres
    password: "040970"
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

app:
  jwt:
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32_CHARS_MIN"
    expirationMinutes: 240
